package org.example.aiinterview.ResumeReadingModel.ResumeController;

import lombok.RequiredArgsConstructor;
import org.example.aiinterview.ResumeReadingModel.ModelEntity.ParsedResume;
import org.example.aiinterview.ResumeReadingModel.ModelEntity.ResumeAnalysis;
import org.example.aiinterview.ResumeReadingModel.ModelEntity.ResumeEntity;
import org.example.aiinterview.ResumeReadingModel.ModelRepo.ResumeRepository;
import org.example.aiinterview.ResumeReadingModel.ModelService.ResumeAnalysisService;
import org.example.aiinterview.ResumeReadingModel.ModelService.ResumeParseService;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.List;

@RestController
@RequestMapping("/api/resume")
@RequiredArgsConstructor
public class ResumeController {
    private final ResumeParseService parseService;
    private final ResumeAnalysisService analysisService;
    private final ResumeRepository resumeRepository;

    @PostMapping("/upload")
    public ResumeEntity uploadResume(
            @RequestParam("file") MultipartFile file,
            @RequestParam String candidateName,
            @RequestParam String email) {

        // Step 1 Parse PDF
        String resumeText =
                parseService.extractText(file);


        // Step 2 AI analysis
        String aiResponse =
                analysisService.analyzeResume(
                        resumeText
                );


        // temporary mapping for MVP
        ParsedResume parsedResume =
                ParsedResume.builder()
                        .resumeText(resumeText)
                        .build();


        ResumeAnalysis analysis =
                ResumeAnalysis.builder()
                        .focusAreas(
                                List.of(aiResponse)
                        )
                        .experienceLevel(
                                "Intermediate"
                        )
                        .questionDifficulty(
                                "Medium"
                        )
                        .strengths(
                                List.of(
                                        "Generated by AI"
                                )
                        )
                        .suggestedTopics(
                                List.of(
                                        "Java",
                                        "Spring Boot"
                                )
                        )
                        .build();


        ResumeEntity resume =
                ResumeEntity.builder()
                        .candidateName(
                                candidateName
                        )
                        .email(email)
                        .parsedResume(
                                parsedResume
                        )
                        .analysis(analysis)
                        .expiresAt(
                                Instant.now()
                                        .plus(
                                                24,
                                                ChronoUnit.HOURS
                                        )
                        )
                        .build();


        return resumeRepository.save(resume);
    }
}
