spring:
  application:
    name: Ai-Interview
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/interview_schedule
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: localhost
      port: 27017
      database: credential_db

server:
  port: 2999
