package org.example.aiinterview.InterViewBookingService.Enums;

public enum Interview_domain {
    FRONTEND_DEVELOPMENT,
    BACKEND_DEVELOPMENT,
    FULL_STACK_DEVELOPMENT,
    DATA_SCIENCE_ML,
    DEVOPS_CLOUD,
    MOBILE_DEVELOPMENT,
    SYSTEM_DESIGN,
    PRODUCT_MANAGEMENT,
    UI_UX_DESIGN,
    QA_TESTING,
    CYBERSECURITY,
    BLOCKCHAIN_DEVELOPMENT,

    HR,
    SALES,
    MARKETING,
    FINANCE,
    CUSTOMER_SUPPORT,
    BUSINESS_ANALYST,
    OPERATIONS,
    CONTENT_WRITING,
    RECRUITMENT,
    NON_TECHNICAL,

    OTHERS

}
